-- This migration was generated out of order and referenced tables that do not
-- exist yet in a fresh database. It is intentionally a no-op so the later
-- create-table migrations can apply successfully.
